services:
  postgres:
    # container_name: postgres
    user: postgres
    restart: always
    build:
      context: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql/data
  backup:
    # container_name: backup
    restart: always
    build:
      context: backup
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - backups:/var/opt/backups
    depends_on:
      - postgres
volumes:
  data:
  backups: